# Game display settings
world:
  scale: 1.0
  width: 1350 # entire window size
  height: 450 # entire viwindowew size
  frame_limit: 60 # fps
  title: "3D Quoridor 2P"
  view:
    size_x: 450.0 # pixels. also the each of the screen size 
    size_y: 450.0 # pixels. also the each of the screen size  
    initial_center:
      x: 0.0 # pixels, absoloute from window
      y: 0.0 # pixels, absoloute from window
  FOV: 60 # degrees
  rays_num: 100 # number of rays
  wall_color: "CUSTOMCOLOR_BROWN"
  
# Game score settings
score:
  initial: 0

# General animation settings
animation:
  change_time: 0.1 # seconds
  passthrough_offset: 65 # pixels

# General sprite and text settings
sprite:
  out_of_bounds_offset: 20 # pixels 
  out_of_bounds_adjustment: 30 # pixels 
  player_y_pos_bounds_run: 440  # SCREEN_HEIGHT - SPRITE_OUT_OF_BOUNDS_ADJUSTMENT

# Sprite paths
sprites:
  sprite1: # player 1
    speed: 40.0
    acceleration:
      x: 1.0 # for 2d space
      y: 1.0 # for 2d space
    jump_acceleration: 
      x: 1.0 # for 2d space
      y: 0.2 # for 2d space 
    index_max: 1 # number of total images for animation 
    animation_rows: 1 # number of rows for animation 
    path: "test/test-assets/sprites/png/1.png"
    position:
      x: 21.0 # pixels 
      y: 225.0 # pixels 
    scale:
      x: 1.0
      y: 1.0
  sprite2: # player 2
    speed: 40.0
    acceleration:
      x: 1.0 # for 2d space
      y: 1.0 # for 2d space
    jump_acceleration: 
      x: 1.0 # for 2d space
      y: 0.2 # for 2d space 
    index_max: 1 # number of total images for animation 
    animation_rows: 1 # number of rows for animation 
    path: "test/test-assets/sprites/png/2.png"
    position:
      x: 430.0 # pixels 
      y: 225.0 # pixels 
    scale:
      x: 1.0
      y: 1.0
  button1:
    index_max: 3 # number of total images for animation 
    animation_rows: 1 # number of rows for animation 
    path: "test/test-assets/sprites/png/button1.png"
    position:
      x: 0.0 # pixels 
      y: 0.0 # pixels 
    scale:
      x: 1.0
      y: 1.0
  pawn_1: # 
    path: "test/test-assets/sprites/png/pawnBlue.png"
    position:
      x: 80.0 # pixels 
      y: 170.0 # pixels 
    scale:
      x: 1.0
      y: 1.0
  pawn_2: 
    path: "test/test-assets/sprites/png/pawnRed.png"
    position:
      x: 80.0 # pixels 
      y: 170.0 # pixels 
    scale:
      x: 1.0
      y: 1.0
  background_big:
    path: "test/test-assets/sprites/png/pathBackground.png"
    position:
      x: 0.0 # pixels 
      y: 0.0 # pixels
    scale:
      x: 1.0
      y: 1.0
  background_big_final:
    path: "test/test-assets/sprites/png/destinationBackground.png" 
    position:
      x: 0.0 # pixels 
      y: 0.0 # pixels
    scale:
      x: 1.0
      y: 1.0
  background_big_half:  
    path: "test/test-assets/sprites/png/half1.png"
    position:
      x: 0.0 # pixels 
      y: 0.0 # pixels
    scale:
      x: 1.0
      y: 1.0
  stick:
    path: "test/test-assets/sprites/png/stick.png"
    spacing: 21 # pixels, spacing between sticks
    starting_position:
      x: -30.0 # pixels
      y: 12
    right_stick_offset_x: -10.0 # pixels, offset for right stick
    right_stick_offset_y: 21.0 # pixels, offset for right stick
    scale:
      x: 1.0
      y: 1.0
   
# Board settings
board:
  tiles_path: "test/test-assets/tiles/png/tilemap1.png"
  scale:
    x: 1.0
    y: 1.0
  tiles_row: 19 # number of rows in the tilemap
  tiles_col: 21 # number of columns in the tilemap
  wall_tileX_index: 0
  wall_tileY_index: 1
  path_tile_index: 2
  p1_goal_tile_index: 3
  p2_goal_tile_index: 4
  blankwall_tile_index: 5
  blank_p1_index: 6
  blank_p2_index: 7
  wall_index: 8
  wall_blank_index: 9
  wall_top_index: 10
  tile_threshold: 6.0 # pixels, threshold for tile movement

# Text settings
text:
  size: 20 # pixels 
  font_path: "test/test-assets/fonts/ttf/font1.ttf"
  message: "Standard Quoridor rule applies.\nPress WASD to move" # actual content in the text
  position:
    x: 20.0 # pixels 
    y: 50.0 # pixels 
  color: "YELLOW" # sf::Color 
ending_text:
  size: 20 # pixels 
  font_path: "test/test-assets/fonts/ttf/font1.ttf"
  message: "" # actual content in the text
  position:
    x: 260.0 # pixels 
    y: 50.0 # pixels 
  color: "RED" # sf::Color
score_text:
  size: 20 # pixels 
  font_path: "test/test-assets/fonts/ttf/font1.ttf"
  message: "Reach the other side to win" # actual content in the text
  position:
    x: 20.0 # pixels 
    y: 10.0 # pixels 
  color: "WHITE" # sf::Color

# Music settings
music:
  background_music:
    path: "test/test-assets/sound/mp3/music1.mp3"
    volume: 80.0 # percent
    ending_volume: 20.0 # percent
    loop: true

# Sound settings
sound:
  button_click: 
    path: "test/test-assets/sound/wav/button.wav"
    volume: 90.0 # percent
 